config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :comments, only: [:create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  resources :friendships, only: [:index, :create, :destroy, :update]
  
  devise_for :users
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :friend_id, uniqueness: { scope: :user_id }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  
  def index
    @sent_friendship_requests = current_user.friendships.where(status: false)
    @received_friendship_requests = current_user.inverse_friendships.where(status: false)
    @real_friends = current_user.friendships.where(status: true)
    friends_ids = current_user.friendships.map {|friend| friend[:friend_id] }
    friends_ids << current_user.id
    @non_friends = User.where.not(:id => friends_ids)
  end
  
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id], status: params[:status])
    if @friendship.save
      flash[:notice] = 'Friend request sent!'
      redirect_to friendships_path
    else
      flash[:notice] = 'Error sending friend request'
      redirect_to friendships_path
    end
  end

  def update
    @friendship = Friendship.find(params[:id])

    if @friendship.update(status: params[:status])
      @inverse_friendship = current_user.friendships.build(friend_id: @friendship[:user_id], status: true)

      if @inverse_friendship.save
        flash[:notice] = 'Friendship accepted'
        redirect_to friendships_path
      else
        flash[:notice] = 'Error creating inverse friend :( '
        render 'users#show'
      end

    else
      flash[:notice] = 'Could not accept friend request'
      render 'users#show'
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @inverse_friendship = Friendship.where(user_id: @friendship.friend_id, friend_id: @friendship.user_id)

    if (current_user.id == @friendship.user_id || current_user.id == @friendship.friend_id)
      @inverse_friendship = Friendship.find_by user_id: @friendship.friend_id, friend_id: @friendship.user_id
      @friendship.destroy
    end

    unless @inverse_friendship.nil?
      @inverse_friendship.destroy
    end

    redirect_to friendships_path

  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<div class="columns">
  <div class="column card is-offset-one-quarter is-half">
    <h1>Pending sent friend requests</h1>
    <ul>
      <% @sent_friendship_requests.each do |friendship| %>
        <li>
          <%= friendship.friend.name %>
          <%= friendship.status %>
          <%= link_to "cancel friend request", friendship_path(id: friendship.id), method: "delete" %>
        </li>
      <% end %>
    
    </ul>
  </div>
</div>

<div class="columns">
  <div class="column card is-offset-one-quarter is-half">
    <h1>Pending received friend requests</h1>
    <ul>
      <% @received_friendship_requests.each do |friendship| %>
        <li>
          <%= friendship.user.name %>
          <%= link_to "accept friend", friendship_path(id: friendship.id, status: true), method: "patch" %>
          <%= link_to "dont accept friend", friendship_path(id: friendship.id), method: "delete" %>
        </li>
      <% end %>
    
    </ul>
  </div>
</div>

<div class="columns">
  <div class="column card is-offset-one-quarter is-half">
    <h1>Friends</h1>
    <ul>
      <% @real_friends.each do |friendship| %>
        <li>
          <%= friendship.friend.name %>
          <%= friendship.status %>
          <%= link_to "Remove friend", friendship_path(id: friendship.id), method: "delete", class: "text-is-danger" %>
        </li>
      <% end %>
    
    </ul>
  </div>
</div>

<div class="columns">
  <div class="column card is-offset-one-quarter is-half">
    <h1> Suggested friends</h1>
    <ul>
      <% @non_friends.each do |user| %>
        <li>
          <%= user.name %>
          <%= link_to "Add friend", friendships_path(friend_id: user.id, status: false), method: "post" %>
        </li>
      <% end %>      
    </ul>
  </div>
</div>