config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :comments, only: [:create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  resources :friendships, only: [:index, :create, :destroy, :update]
  
  devise_for :users
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true
  validates :author_id, presence: true

  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes, as: :likeable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    friends_ids = current_user.friendships.map {|friend| friend[:friend_id] }
    friends_ids << current_user.id
    @posts = Post.where(author_id: friends_ids).order(last_comment_at: :desc)

    @post = Post.new
    @comment = Comment.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post[:author_id] = current_user[:id]

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
      else
        format.html { redirect_to posts_path }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :author_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% unless notice.nil? %>
  <p class="notification is-warning" sid="notice"><%= notice %></p>
<% end %>

<section id="new-post-form" class="columns">

  <div class="column is-one-quarter">
    <%= link_to "Friends", friendships_path, class: "button ml-3 is-primary" %>
  </div>


  <div class="column is-half card">
    <%= form_with model: @post, local: true do |form| %>
      <div class="field">
        <%= form.label :body, "New post", class: "label"%>
        <div class="control">
          <%= form.text_area :body, class: "textarea" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= form.submit class: "button" %>
        </div>
      </div>
    <% end %>
  </div>
</section>


<section class="columns" id="posts">
  <div class="card column is-half is-offset-one-quarter">
    <% @posts.each do |post| %>
      <article class="media">
        <figure class="media-left">
          <% if post.author.avatar.attached? && post.author.avatar.representable? %>
            <p class="image is-64x64">
              <%= image_tag post.author.avatar.variant(resize_to_limit: [64, 64])%>
            </p>            
          <% else %>
          <p class="image is-64x64">
            <%= image_tag ("pipboy.jpeg")%>
          </p>
          <% end %>
        </figure>
        <div class="media-content">
          <div class="content">
            <h1 class="title is-5"><%= post.author.name %></h1>
            <h2 class="subtitle is-7">
              <%= link_to "go to post", post_path(post[:id], method: "get") %>
            </h2>
            <p class="is-family-primary">
              <p> <%= post.last_comment_at %> </p>
              <%= post.body %> 
            </p>
          </div>
          <nav class="level">
            <div class="level-left">
              <p class="level-item has-text-info">Likes <%= post.likes.count %></p>
              <% if post.likes.find_by(user_id: current_user.id) %>
                <%= link_to icon('fas', 'thumbs-up'), post_like_path(post_id: post.id, id: post.likes.find_by(user_id: current_user.id).id), method: "delete", class: "level-item"%>
              <% else %>
                <%= link_to icon('far', 'thumbs-up') , post_likes_path(post_id: post.id), method: "post", class: "level-item" %>
              <% end %>
            </div>
          </nav>

          <% post.comments.each do |comment| %>
            <article class="media">
              <figure class="media-left">
                <p class="image is-32x32">
                  <%= image_tag ("pipboy.jpeg")%>
                </p>
              </figure>
              <div class="media-content">
                <div class="content">
                  <h2 class="title is-6">
                    <strong><%= comment.author.name %></strong>
                  </h2>
                  <p class="is-family-primary"> 
                    <%= comment.content %> 
                  </p>
                </div>

                <nav class="level">
                  <div class="level-left">
                    <p class="level-item has-text-info">Likes <%= comment.likes.count %></p>
                    <% if comment.likes.find_by(user_id: current_user.id) %>
                      <%= link_to icon('fas', 'thumbs-up'), comment_like_path(comment_id: comment.id, id: comment.likes.find_by(user_id: current_user.id).id), method: "delete", class: "level-item"%>
                    <% else %>
                      <%= link_to icon('far', 'thumbs-up') , comment_likes_path(comment_id: comment.id), method: "post", class: "level-item" %>
                    <% end %>
                  </div>
                </nav>

              </div>            
            </article>
          <% end %>
        </div>
        
        
      </article>
      <article class="media">
          <div class="media-content">
            <%= form_with model: @comment, local: true do |form| %>
              <%= form.hidden_field :post_id, value: post[:id] %>
              <div class="field">
                <div class="control">
                  <%= form.text_area :content, class: "textarea" %>
                </div>
              </div>
              <div class="field">
                <div class="control">
                  <%= form.submit class: "button" %>
                </div>
              </div>
            <% end %>
                
          </div>
        </article>
    <% end %>
  </div>
</section>

app/views/posts/show.html.erb
<section class="columns" id="posts">
  <div class="card column is-half is-offset-one-quarter">
    <article class="media">
      <figure class="media-left">
        <p class="image is-64x64">
          <%= image_tag ("pipboy.jpeg")%>
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <h2 class="title is-4">
            <strong><%= @post.author.name %></strong>
          </h2>
          <p class="is-family-primary"> 
            <%= @post.body %> 
          </p>
        </div>

        <% @post.comments.each do |comment| %>
          <article class="media">
            <figure class="media-left">
              <p class="image is-32x32">
                <%= image_tag ("pipboy.jpeg")%>
              </p>
            </figure>
            <div class="media-content">
              <div class="content">
                <h2 class="title is-6">
                  <strong><%= comment.author.name %></strong>
                </h2>
                <p class="is-family-primary"> 
                  <%= comment.content %> 
                </p>
              </div>
            </div>            
          </article>
        <% end %>
      </div>
    </article>
  </div>
</section>